/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { ContractAbi, ContractAbiInterface } from "../ContractAbi";
const _abi = [
  {
    type: "function",
    name: "deposit",
    inputs: [],
    outputs: [
      {
        type: "struct Deposit",
        name: "",
        components: [
          {
            type: "u64",
            name: "id",
          },
          {
            type: "u64",
            name: "amount",
          },
          {
            type: "enum Identity",
            name: "owner",
            components: [
              {
                type: "struct Address",
                name: "Address",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
              {
                type: "struct ContractId",
                name: "ContractId",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
            ],
          },
          {
            type: "bool",
            name: "isValid",
          },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      {
        type: "u64",
        name: "depositId",
      },
    ],
    outputs: [
      {
        type: "struct Deposit",
        name: "",
        components: [
          {
            type: "u64",
            name: "id",
          },
          {
            type: "u64",
            name: "amount",
          },
          {
            type: "enum Identity",
            name: "owner",
            components: [
              {
                type: "struct Address",
                name: "Address",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
              {
                type: "struct ContractId",
                name: "ContractId",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
            ],
          },
          {
            type: "bool",
            name: "isValid",
          },
        ],
      },
    ],
  },
];

export class ContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ContractAbiInterface {
    return new Interface(_abi) as unknown as ContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): ContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as ContractAbi;
  }
}
